#!/usr/bin/perl -w

if ("" eq $ARGV[0]) {
prhelp:
print <<"EOM";
Prepares barChart data for GNUPlot/Plotutils.

Usage:

barChart [-wo value [value]] ... [inputfile] ...

where fieldnames must match fieldnames in first line of the datafile.

-w, --barwidth  value
	Specifies bar width.
-o, --baroffset
	Specifies bar offset.

EOM
exit;
}

%operand=(w => 1, o => 1, wo => 2, ow => 2,);						# supported switches and # of parameters
%longoperand=('-barwidth'		=> 'w', '-baroffset'	=> 'o',);	# long option names and equivalent shorts

$interval = 1.0;
$offset = 0.0;

while ($_ = $ARGV[0], /^-/)
	{
	s/^-//;
	if ($longoperand{$_}) { $_=$longoperand{$_}; }
	exists ($operand{$_}) || die "Argument -$_ not supported.\n";
	if ("" eq $ARGV[$operand{$_} - 1]) { die "Missing parameter for -$_.\n"; }
	shift;
	if ("w"  eq $_)	{ $interval = $ARGV[0]; }
	if ("o"  eq $_)	{ $offset   = $ARGV[0]; }
	if ("wo" eq $_)	{ $interval = $ARGV[0]; $offset = $ARGV[1]; shift; }
	if ("ow" eq $_)	{ $interval = $ARGV[1]; $offset = $ARGV[0]; shift; }
	shift;
	}

$interval = $interval / 2.0;
while (<>)
	{
	chomp;
	s/\#.*//;
	s/^ *//;
	if (/^$/) { next; }

	($x,  $y)=split(/\s+/, $_);

	print $x-$interval + $offset, "\t$y\n";
	print $x+$interval + $offset, "\t$y\n";
	}
