#!/usr/bin/perl -w

if ("" eq $ARGV[0])
{
prhelp:
print <<"EOM";
Prepares graph boxplot data.

Usage:

boxplot [-w  width] [input] ...

-w, --width
EOM
exit;
}

$factor = 1.0;

while ($_ = $ARGV[0], /^-/)
	{
	if (($ARGV[0] eq "-w") || ($ARGV[0] eq "--width"))
		{
		$factor= $ARGV[1];
		shift;
		}
	shift;
	}

$mdelta  = 0.05  * $factor;
$afdelta = 0.075 * $factor;
$kdelta  = 0.1   * $factor;

while (<>) {
	chomp;
	s/\#.*//;
	s/^ *//;
	if (/^$/) { next; }

	($x, $kozep, $min, $max, $also, $felso)=split(/\s+/, $_);

	#$x -= 0.5;

	print $x-$mdelta, "\t$min\n", $x+$mdelta, "\t$min\n\n";
	print $x-$mdelta, "\t$max\n", $x+$mdelta, "\t$max\n\n";
	print "$x\t$min\n$x\t$max\n\n";

	print $x-$kdelta, "\t$kozep\n", $x+$kdelta, "\t$kozep\n\n";

	print $x-$afdelta, "\t$also\n", $x+$afdelta, "\t$also\n";
	print $x+$afdelta, "\t$felso\n", $x-$afdelta, "\t$felso\n";
	print $x-$afdelta, "\t$also\n\n";
}

